### ISSUE TITLE
Azure Functionsの設置

### ISSUE THREAD

**Issue by reone19** [hal-tokyo-cello/cello-functions#13]
# FunctionsのCI/CD
functions.ymlファイルは完成
# npmの設定について
```yml:functions.yml
name: functions

# main ブランチに何らかの commit が追加されたら走らせる
on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: HAL-TH22-IH4C-IW4C-G01-functions01-yoshida # functionsの名前。書き換えてください
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./" # アップロードするディレクトリ。書き換えてください（現在はルートディレクトリすべてをデプロイしている）
  NODE_VERSION: "16.x" # nodeのバージョンを指定。書き換えてください

jobs:
  functions-build-and-deploy:
    name: Functions-build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Resolve Project Dependencies Using Npm
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.FUNCTIONS_NAGIDERBY }} # プロファイラを登録したNAMEを指定してください

```
ここの
name: Resolve Project Dependencies Using Npm
項目について、バックがどのように開発しているのか分からないので、何を書けばいいのか分かりません。
バックに投げていいですか。
